name: Python application
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage

      - name: Run tests with coverage
        run: |
          pytest --cov=app tests/

      - name: Enforce 100% coverage
        run: |
          coverage report --fail-under=100
          coverage html
          echo "Preview of generated HTML coverage files:"
          ls -R htmlcov | head -20
